ITM-539:  Break action mapping conditions into probe and action conditions
NextCenturyCorporation/itm-evaluation-client pull request #59
Opened 2024-08-02 20:04 UTC by nextcen-dgemoets

Please see the [server PR](https://github.com/NextCenturyCorporation/itm-evaluation-server/pull/99).

Although there are a lot of touched files here, the only change is an updated swagger file to match the server, regenerating all files, and updating the README.  Because of the API version change (one increment per release), it regenerates a lot of files.

2024-08-05 16:16 UTC, phile-caci approved these changes
LGTM, not seeing any issues on my end from the client.

Ran through
- python itm_minimal_runner.py --name foobar --session test --scenario conditional_mappings
- python itm_human_input.py --session test --scenario conditional_mappings


Also ran the following for regression, no issues:
```
python itm_minimal_runner.py --name foobar --session adept 
python itm_minimal_runner.py --name foobar --session adept --training 
python itm_minimal_runner.py --name foobar --session soartech 
```

2024-08-06 14:11 UTC, phile-caci requested changes
Re-Tested with new SoarTech stuff:

**This now works:**
python itm_minimal_runner.py --name foobar --session soartech --training 


**Re-ran, no issues:**
python itm_minimal_runner.py --name foobar --session adept 
python itm_minimal_runner.py --name foobar --session adept --training 
python itm_minimal_runner.py --name foobar --session soartech 
python itm_minimal_runner.py --name foobar --session test --scenario conditional_mappings

2024-08-06 14:11 UTC, phile-caci approved these changes

2024-08-06 14:15 UTC, brianpippin approved these changes

2024-08-06 14:22 UTC, merged